// @quartal/create-plugin/templates/widgets/react/SayHello.tsx
import { useEffect, useState } from "react";
import { connectWidget } from "@quartal/plugin/widget";

/**
 * Widget for the `sayHello` tool: the MCP host runs the tool and delivers the result
 * (the greeting string) over the framework-agnostic `@quartal/plugin/widget` bridge.
 */
export default function SayHello() {
  const [result, setResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    void connectWidget<string>({
      name: "SayHelloApp",
      version: "0.1.0",
      onResult: (greeting) => {
        setResult(greeting);
        setError(null);
      },
      onError: setError,
    });
  }, []);

  const style = { fontFamily: "system-ui, sans-serif", padding: "1rem" };
  if (error) {
    return (
      <div style={style} role="alert">
        {error}
      </div>
    );
  }
  return <div style={style}>{result ? <h2>{result}</h2> : "Waiting for the tool result…"}</div>;
}

// @quartal/create-plugin/templates/widgets/vue/SayHello.vue
<script setup lang="ts">
import { useExtApps } from "@quartal/plugin-vue";

// Widget for the `sayHello` tool: the MCP host runs the tool and delivers the result
// (the greeting string) to this component over the MCP Apps bridge.
const { result, error } = useExtApps<string>({
  name: "SayHelloApp",
  version: "0.1.0",
});
</script>

<template>
  <div class="q-say-hello">
    <div v-if="error" class="error" role="alert">{{ error }}</div>
    <h2 v-else-if="result">{{ result }}</h2>
    <div v-else>Waiting for the tool result…</div>
  </div>
</template>

<style scoped>
.q-say-hello {
  font-family: system-ui, sans-serif;
  padding: 1rem;
}
.error {
  color: #b3261e;
}
:global(html[data-theme="dark"]) .error {
  color: #ffb4ab;
}
</style>
